@baseUrl = http://localhost:4000
@authToken = {{authToken}}

### ================== RESOURCES ==================

### Crear recurso (publico)
POST {{baseUrl}}/api/resource/public
Content-Type: application/json

{
  "path": "/api/pacientes/public",
  "method": "GET",
  "is_active": "ACTIVE"
}


### Listar recursos (publico)
GET {{baseUrl}}/api/resources/public
Accept: application/json

### Obtener recurso por id (publico)
GET {{baseUrl}}/api/resource/1/public
Accept: application/json

### Actualizar recurso (publico)
PATCH {{baseUrl}}/api/resource/1/public
Content-Type: application/json

{
  "method": "POST",
  "is_active": "ACTIVE"
}

### Eliminar recurso fisicamente (publico)
DELETE {{baseUrl}}/api/resource/1/public

### Baja logica de recurso (publico)
PATCH {{baseUrl}}/api/resource/1/logic/public
Content-Type: application/json

{
  "is_active": "INACTIVE"
}

### Crear recurso (con auth)
POST {{baseUrl}}/api/resource
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "path": "/api/doctor",
  "method": "PATCH",
  "is_active": "ACTIVE"
}

### Listar recursos (con auth)
GET {{baseUrl}}/api/resources
Authorization: Bearer {{authToken}}
Accept: application/json

### Obtener recurso por id (con auth)
GET {{baseUrl}}/api/resource/1
Authorization: Bearer {{authToken}}
Accept: application/json

### Actualizar recurso (con auth)
PATCH {{baseUrl}}/api/resource/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "method": "DELETE",
  "is_active": "ACTIVE"
}

### Eliminar recurso fisicamente (con auth)
DELETE {{baseUrl}}/api/resource/1
Authorization: Bearer {{authToken}}

### Baja logica de recurso (con auth)
PATCH {{baseUrl}}/api/resource/1/logic
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "is_active": "INACTIVE"
}
